stages:
  - build
  - test

Build the Docker Image:
  variables:
    DOCKER_HOST: 'unix:///var/run/docker.sock'
  image: docker:dind
  stage: build
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - dockerd-entrypoint.sh &
    - sleep 3
    - docker pull ${CI_REGISTRY_IMAGE}:latest > /dev/null 2>&1
    - docker build --cache-from ${CI_REGISTRY_IMAGE}:latest --tag ${CI_REGISTRY_IMAGE}:latest .
    - docker push ${CI_REGISTRY_IMAGE}:latest

Test the service:
  stage: test
  services:
    - name: ${CI_REGISTRY_IMAGE}:latest
      alias: server
  script:
    - curl -sSL http://server:3000/ok
